### PR TITLE
Add clarification for 2018 AHM training

### PR DESCRIPTION
**Pull request by brianhlin**
@rynge: I spoke with Rob G about running a user training Thursday morning of the AHM and he said he'd ping you. Let me know if you have anything to add to this PR.

### CODE REVIEW

**Comment by osg-cat** [comment]
Isn’t the out-of-table comment going to render as a bullet? How about making it a proper asterisk or even admonition note.

**Review by osg-cat — COMMENTED** [review]
I left a comment already.

**Comment by osg-cat** [comment]
I made some changes to your changes. OK?

**Comment by brianhlin** [comment]
LGTM

**Pull request merged**
