### PR TITLE
Initial COVID page

### PR DESCRIPTION
**Pull request by osg-cat**

### CODE REVIEW

**Review by jstathas — COMMENTED** [review]
I would incorporate this text re Q1 so that you don't force the user to review all OU Together unless desired. "Community members are expected to mask indoors, especially in high-density settings, such as classrooms and at special events when not eating or drinking."

**Comment by osg-cat** [comment]
That’s tricky, right? I’m not sure that I want us to be responsible for summarizing OU’s policies and staying on top of their changes. What if we get it wrong? Who’s fault is that, then?

**Comment by jstathas** [comment]
Yes, I understand that  - so dating it and other caveat text would be in order, but it goes back to the don't make me think - two clicks in and multiple choices on where to go.



Janet Stathas
PATh Project Manager
Morgridge Institute for Research

Email: ***@***.******@***.***>
Cell:  608.345.9605

https://morgridge.org<https://morgridge.org/>
https://path-cc.io/


________________________________

**Comment by osg-cat** [comment]
I have no interest in exposing OSG to potential mistakes here, nor the additional verbiage that it would take to cover ourselves. But if you feel strongly about it … then I guess that’s between you and Frank.

**Comment by osg-cat** [comment]
Merging as-is, we can always update later.

**Pull request merged**
